// Centralized icon exports using require for better stability
const Icons = {
  Acceder: require('./Acceder.png'),
  Accepted: require('./Accepted.png'),
  Ajouts: require('./Ajouts.png'),
  Checked: require('./Checked.png'),
  Download: require('./Download.png'),
  Fermer: require('./Fermer.png'),
  Filtre: require('./Filtre.png'),
  Gift: require('./Gift.png'),
  Infos: require('./Infos.png'),
  LogOut: require('./Log-out.png'),
  Modifier: require('./Modifier.png'),
  NotChecked: require('./Not-checked.png'),
  Outils: require('./Outils.png'),
  Partager: require('./Partager.png'),
  Participant: require('./Participant.png'),
  PasVu: require('./Pas-vu.png'),
  Paysage: require('./Paysage.png'),
  Portrait: require('./Portrait.png'),
  Print: require('./Print.png'),
  Profil: require('./Profil.png'),
  Rechercher: require('./Rechercher.png'),
  Refuse: require('./Refuse.png'),
  Rejected: require('./Rejected.png'),
  Retour: require('./Retour.png'),
  Scan: require('./Scan.png'),
  ScanCamera: require('./ScanCamera.png'),
  Supp: require('./Supp.png'),
  Verifie: require('./Verifie.png'),
  Vu: require('./Vu.png'),
  checkedIn: require('./checkedIn.png'),
  closeButton: require('./closeButton.png'),
  refresh: require('./refresh.png'),
  totalAttendees: require('./totalAttendees.png'),
  stats: require('./Stats.png'),
  notAttended: require('./notAttended.png'),
};

export default Icons;
